export const BASE_URL = "http://13.229.222.26:8000/"
export const REGISTER_URL = BASE_URL + "api/v1/create_user/"
export const LOGIN_URL = BASE_URL + "api/v1/users/login/"
export const GET_USER = BASE_URL + "api/v1/users/get_user/"
    // create cashier, moderator.
export const CREATE_EMPLOYEE = BASE_URL + "api/v1/users/create_employee/"
export const GET_LIST_CASHIER = BASE_URL + "api/v1/users/get_list_cashier/"
export const GET_LIST_MODERATOR = BASE_URL + "api/v1/users/get_list_moderator/"
export const GET_CASHIER = BASE_URL + "api/v1/users/get_cashier/"
export const GET_MODERATOR = BASE_URL + "api/v1/users/get_moderator/"
export const DELETE_USER = BASE_URL + "api/v1/users/get_user/"
export const GET_SYSTEMS_USER = BASE_URL + "api/v1/users/get_users/"
export const GET_ROLES = BASE_URL + "api/v1/users/get_roles/"

// Sơn
export const CREATE_PRODUCT = BASE_URL + "api/v1/product/create_new/"
export const GET_LIST_TABLE_PRODUCT = BASE_URL + "api/v1/product/get_products/"
export const GET_PRODUCT_DETAIL = BASE_URL + "api/v1/product/get_product/"
export const DELETE_PRODUCT = BASE_URL + "api/v1/product/get_product/?product_id="
export const UPDATE_PRODUCT = BASE_URL + "api/v1/product/get_product/?product_id="